#!/bin/bash -ex
#
# script/bootstrap
# mas
#
# Installs gem tools, installs Swift dependencies via CocoaPods and sorts
# the Xcode project file references.
#

main() {
  echo "==> 👢 Bootstrapping"
  bundle install
  bundle exec pod install --repo-update

  script/sort
}

main
