#!/bin/bash -ex
#
# script/build
# mas
#
# Builds the Xcode project. The xcpretty gem is used to format the build log.
#
# If the TRAVIS_TAG env variable is present, it generates an archive.
# https://docs.travis-ci.com/user/environment-variables/#default-environment-variables
#

BUILD_DIR="$PWD/build"
WORKSPACE="mas-cli.xcworkspace"
SCHEME="mas-cli Release"
CONFIG="Release"

main() {
  script/clean

  xcodebuild -workspace "$WORKSPACE" \
    -scheme "$SCHEME" \
    -configuration "$CONFIG" \
    clean

  build

  # TEMP: Archive is invoked on every build to limit the number of files that need to be
  # uploaded/downloaded from S3 due to how travisci stages work.
  # If this is a tagged build we are going to release
#   TEMP: Generate archive on all builds
#   if [[ ! -z $TRAVIS_TAG ]]; then
    archive
#   fi
}

build() {
  echo "==> 🏗️ Building"
  set -o pipefail && \
      xcodebuild -workspace "$WORKSPACE" \
          -scheme "$SCHEME" \
          -configuration "$CONFIG" \
          OBJROOT="$BUILD_DIR/obj" \
          SHARED_PRECOMPS_DIR="$OBJROOT/SharedPrecompiledHeaders" \
          SYMROOT="$BUILD_DIR/sym" \
          build \
      | bundle exec xcpretty --color
}

archive() {
  echo "==> 📦 Archiving"
  set -o pipefail && \
      xcodebuild -workspace "$WORKSPACE" \
          -scheme "$SCHEME" \
          -configuration "$CONFIG" \
          -archivePath "$BUILD_DIR/mas.xcarchive" \
          OBJROOT="$BUILD_DIR/obj" \
          SHARED_PRECOMPS_DIR="$OBJROOT/SharedPrecompiledHeaders" \
          SYMROOT="$BUILD_DIR/sym" \
          archive \
      | bundle exec xcpretty --color
}

main
