#!/bin/bash -ex
#
# script/package
# mas
#
# Adds symbol files to xcarchive, compresses xcarchive and mas executable,
# and finally prints the sha256 of the compressed binary.
#

BUILD_DIR=build
SYM_DIR=sym/Release

pushd $BUILD_DIR

echo "==> 🚚 Moving dSYM to xcarchive"
mkdir -p mas.xcarchive/dSYMs/
mv $SYM_DIR/mas.dSYM mas.xcarchive/dSYMs/

echo "==> 🗜️ Compressing mas.xcarchive"
zip -r mas.xcarchive.zip mas.xcarchive

echo "==> ️🗜️ Compressing binary"
zip -j mas-cli.zip mas.xcarchive/Products/build/mas

echo -n "==> 🔢 SHA256: "
shasum -a 256 mas-cli.zip

popd
